# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4cf658fc798ca882162c00a60b2a26ee4c260b963fdf67717844c72a8ed280fda632f89f41e27910f7e7626723c051c7feffa3c8afc9f8ce7cb47f13c030c23

test:
  secret_key_base: 83a1ee9baba770164bb0bd6e2fd43c8f17c964b6793f015b75b6c5fa3ca45cea804d67c030ecce0a3ba26351ea05bab93dadfe4b0e3bc7978df5f4349d82f036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
